INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (782140661, 'OCP: Oracle9i Certification Kit', 2);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (72227885, 'SQL Server 2000 for Experienced DBA''s', 5);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (471200247, 'The Data Warehouse Toolkit: The Complete Guide to Dimensional Modeling', 28);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (72227710, 'How To Do Everything with Your Tablet PC', 8);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (1558605525, 'Data Mining: Practical Machine Learning Tools and Techniques with Java Implementations', 1);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (972263608, 'Creating Documents with BusinessObjects 5.1', 0);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (201615762, 'The Guru''s Guide to Transact-SQL', 8);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (782140114, 'Access 2002 Developer''s Handbook Set', 5);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (321125169, 'ColdFusion MX Web Application Construction Kit', 7);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (805317554, 'Fundamentals of Database Systems ', 2);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (61092177, 'Small Gods', 14);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (60502935, 'Going Postal', 16);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (61020656, 'Pyramids', 2);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (60855925, 'The Color of Magic', 8);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (61020648, 'Guards! Guards!', 9);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (61161721, 'Unseen Academicals', 20);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (1861004486, 'Investing in Fixer-Uppers : A Complete Guide to Buying Low, Fixing Smart, Adding Value, and Selling (or Renting) High', 27);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (735712123, 'MySQL', 49);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (425188361, 'Cerulean Sins', 45);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (142001740, 'The Secret Life of Bees', 15);
INSERT INTO "Inventory Info For All Books" (ISBN, title, quantity) VALUES (596004478, 'Google Hacks', 38);