INSERT INTO NAMES (id, fname, lname, mname) VALUES (1, 'Chip', 'Dawes', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (2, 'Biju', 'Thomas', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (3, 'Doug', 'Stuns', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (4, 'Matthew', 'Weishan', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (5, 'Joseph', 'Johnson', 'C');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (6, 'Brian', 'Knight', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (7, 'Ralph', 'Kimball', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (8, 'Margy', 'Ross', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (9, 'Bill', 'Mann', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (10, 'Ian', 'Witten', 'H');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (11, 'Eibe', 'Frank', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (12, 'Robert', 'Schmidt', 'D');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (13, 'Ken', 'Henderson', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (14, 'Paul', 'Litwin', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (15, 'Ken', 'Getz', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (16, 'Mike', 'Gunderloy', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (17, 'Ben', 'Forta', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (18, 'Nate', 'Weiss', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (19, 'Leon', 'Chalnick', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (20, 'Angela', 'Buraglia', 'C');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (21, 'Ramez', 'Elmasri', 'A');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (22, 'Shamkant', 'Navathe', 'B');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (23, 'Jane', 'Gonzalez', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (24, 'Shawn', 'Taylor', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (25, 'Kathleen ', 'Cook', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (26, 'Philip ', 'Turner', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (27, 'Thomas', 'Hernandez', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (28, 'Fred ', 'King', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (29, 'Earl ', 'Roberts', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (30, 'Gregory ', 'Garcia', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (31, 'Phyllis ', 'Phillips', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (32, 'Louis ', 'Bailey', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (33, 'Mary ', 'Cooper', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (34, 'Laura ', 'Wright', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (35, 'Richard ', 'Miller', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (36, 'John ', 'Lewis', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (37, 'Maria ', 'Davis', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (38, 'Aaron ', 'Hill', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (39, 'Scott ', 'Coleman', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (40, 'Donald ', 'Bryant', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (41, 'Larry ', 'Martin', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (42, 'George ', 'Long', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (43, 'Rebecca ', 'Jackson', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (44, 'Eugene ', 'Morris', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (45, 'Roy ', 'Reed', '');
INSERT INTO NAMES (id, fname, lname, mname) VALUES (46, 'Terry', 'Pratchett', null);