INSERT INTO PUBLISHERS (pid, publisher) VALUES (1, 'Sybex');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (2, 'McGraw-Hill Osborne Media');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (3, 'John Wiley & Sons');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (4, 'Morgan Kaufmann');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (5, 'Schmidt Ink, Inc.');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (6, 'Addison-Wesley Pub Co');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (7, 'Macromedia Press');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (8, 'Navathe');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (9, 'Wrox Press Inc');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (10, 'Berkley Pub Group');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (11, 'Penguin USA ');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (12, 'O''Reilly & Associates');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (13, 'McGraw-Hill Trade');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (14, 'Picador');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (15, 'St. Martin''s Press');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (16, 'Crown Pub');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (17, 'Little Brown & Company');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (18, 'Simon & Schuster');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (19, 'HarperCollins');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (20, 'Jossey-Bass');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (21, 'Multnomah Publishers Inc.');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (22, 'Perennial');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (23, 'Dell Pub Co');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (24, 'Harlequin');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (25, 'Viking Press');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (26, 'Perseus Publishing');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (27, 'Random House');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (28, 'Knopf');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (29, 'Wolfram Media, Inc.');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (30, 'Fireside');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (31, 'lams');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (32, 'Gibbs Smith Publisher');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (33, 'Taunton Pr');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (34, 'Vendome Pr');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (35, 'Clarkson N. Potter');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (36, 'MIT Press');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (37, 'McGraw-Hill/Irwin');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (38, 'South-Western College Pub');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (39, 'Prentice Hall');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (40, 'Warner Books');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (41, 'Scribner');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (42, 'Pocket Books');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (43, 'Pantheon Books');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (44, 'Del Rey');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (45, 'Doubleday');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (46, 'Donald M. Grant Publisher, Inc.');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (47, 'Vintage Books');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (48, 'Scribner Paperback Fiction');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (49, 'Harvest Books');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (50, 'Harperperennial Library');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (51, 'W.W. Norton & Company');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (52, 'Harvard Univ Pr');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (53, 'Prentice Hall PTR');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (54, 'New Riders Publishing');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (55, 'Ballantine Books ');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (56, 'Back Bay Books');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (57, 'Anchor Books');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (58, 'Putnam Pub Group');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (59, 'Silhouette');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (60, 'Lark Books');
INSERT INTO PUBLISHERS (pid, publisher) VALUES (61, 'Harper');